### ISSUE TITLE
Invalid Signature Error on Callback

### ISSUE THREAD

**Issue by chrisgrande** [mastizada/dj-twilio-sms#10]
Callback failing with Error 403 - Invalid signature. Have you seen this before?

**Comment by mastizada** [comment]
Have you added the callback url (domain) to the whitelist in Twilio?
In Programmable SMS settings, there is `STATUS CALLBACK URL` field in `Outbound Settings`

**Comment by mastizada** [comment]
https://www.twilio.com/docs/authy/return-and-error-codes

**Comment by chrisgrande** [comment]
Yes, it's calling the correct URL but it's returning 'invalid signature' as the error... which is odd. I'm not sure what that could be.

**Comment by chrisgrande** [comment]
Was caused by the internal address being generated not matching the callback URL.

**Comment by mastizada** [comment]
Thanks)
