### ISSUE TITLE
Outgoing API Error

### ISSUE THREAD

**Issue by chrisgrande** [mastizada/dj-twilio-sms#4]
I'm not sure what the issue is, but when running the included test I get the error:

/dj_twilio_sms/tests.py", line 20, in test_send_sms
    self.assertEqual(result.created_at.tzinfo, UTC)
AssertionError: None != <UTC>

on Twilio's logs: Missing META param: u'HTTP_X_TWILIO_SSL'

**Comment by mastizada** [comment]
Hi, thanks for checking. Second issue was twilio related and should be solved in branch `issue-4`
The first one is due to missing TimeZone in created_at field. What is the value of `USE_TZ` in your settings?

**Comment by chrisgrande** [comment]
I implemented the change in issue-4 and Twilio now reports "Invalid Signature". I have no USE_TZ setting so it's in effect set to 'False'.

**Comment by chrisgrande** [comment]
See #5 for Invalid Signature fix. Caused by no HTTP_X_TWILIO_SSL Meta tag so the URL is never constructed with https, causing the locally generated signature to not match the sent signature.

**Comment by mastizada** [comment]
Solved on version 2.0

**Comment by mastizada** [comment]
@chrisgrande @truhlik @nigma @lanshark can you verify the last version for incoming messages?

**Comment by chrisgrande** [comment]
Just got back and around to testing, incoming and outgoing seem to work with no issue. 

On the incoming view, the code comments:
#Override to add custom logic and configure url in the Twilio admin panel.

What's the best way to achieve this override?

**Comment by mastizada** [comment]
Idea is to extend class and rewrite `def post_save(self)` function. Can be used for auto reply or confirmation or anything else.

**Comment by chrisgrande** [comment]
Oh so just write a new function with it's own url endpoint and point Twilio at that, makes sense. I was thinking I was missing something! Thanks for the updates for the new API. 👍

**Comment by mastizada** [comment]
Thank you @chrisgrande for reporting the problem.
