### ISSUE TITLE
serizalization issue in get_response()

### ISSUE THREAD

**Issue by truhlik** [mastizada/dj-twilio-sms#8]
Hi,

I have a problem with TwilioView.get_response(). Every response ends with 500 because of serialization issue. See details below.

> File "python2.7/site-packages/dj_twilio_sms/views.py", line 50, in get_response
>     response = HttpResponse(str(response), content_type='application/xml')
> 
> TypeError: cannot serialize <twilio.twiml.messaging_response.Body object at 0x7f2122fdd710> (type Body)
> 

I change message.response to this `response.message(response_text)` and it's working fine again.

But seems strange to me, that this issues wasn't noticed yet by anyone else. Can you look at it?

Thank you,
Lubos

**Comment by mastizada** [comment]
Thanks for reporting. Solved in version 2.1.0. Released in pypi
